### PR TITLE
PDCL-6239: Update direct call action with detail

### LINKED ISSUE #38: "Trigger Direct Call" action type supports wrong `event`
The "Trigger Direct Call" action type (see #23) allows `_satellite.track()` to be triggered without writing custom code.

### Expected Behaviour

https://experienceleague.adobe.com/docs/experience-platform/tags/client-side/satellite-object.html?lang=en

### Actual Behaviour
The "Trigger Direct Call" action type uses the event object of the calling Rule as its second argument. However, this event object is set automatically by the Rule, whereas the expectation when using `_satellite.track()` is that you can send your own custom event object in the second argument.

https://github.com/adobe/reactor-extension-core/blob/213989a7d9895871c5a1640ab9dde38da7822dac/src/lib/actions/directCall.js#L27-L31

### Reproduce Scenario (including but not limited to)
See Sample Code below.

#### Steps to Reproduce
See Sample Code below.

#### Platform and Version
All

#### Sample Code that illustrates the problem
Expected usage with Direct Calls:
``{{
var detail = { name: 'John Doe' };
_satellite.track("identifier", detail); // detail is a custom event object
}}``

#### Logs taken while reproducing problem
N/A

### PR DESCRIPTION
**Pull request by brenthosie**
## Related Issue

https://jira.corp.adobe.com/browse/PDCL-6239

## Motivation and Context

Resolves #38 
Closes #47 

Allows the user to specify event context from the triggering direct call action to other direct call events/rule flows.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] I have [updated the Experience League documentation](https://git.corp.adobe.com/AdobeDocs/experience-platform.en/pull/2368) for the [Core Extension](https://git.corp.adobe.com/AdobeDocs/experience-platform.en/tree/master/help/tags/extensions/web/core)
- [x] All tests pass and I've made any necessary test changes.
- [x] I have run the extension sandbox successfully.

### CODE REVIEW

File: src/view/actions/directCall.jsx [hunk 1]
```diff
@@ -11,41 +11,194 @@
...
-    errors = {
-      ...errors
-    };
+    errors = { ...errors };
 
     if (!values.identifier) {
       errors.identifier = 'Please specify an identifier.';
     }
 
+    errors.eventObjectEntries = [];
```
Comment (dompuiu) [inline src/view/actions/directCall.jsx:186]: This validation is more strict than what you have defined in the JSON Schema. In the view the `value` key is required while in the JSON schema it is not. I think they should match. At the current state, using the API I can add settings objects that the view would consider them invalid.

Comment (dompuiu) [reply src/view/actions/directCall.jsx:186]: You could consider adding a validation that would check that the keys are unique. Having 2 keys with the same name would not break the functionality, but it would be nice to tell the user that he should clean up.

File: src/view/actions/directCall.jsx [hunk 2]
```diff
@@ -11,41 +11,194 @@
...
+              <em>
+                {String.fromCharCode(FORWARD_SLASH)}&nbsp;
+                {String.fromCharCode(FORWARD_SLASH)}&nbsp; (optional) - enhance
+                the direct call with this information
+              </em>
+            </span>
+            <span className="codeLine">
+              const detail = {String.fromCharCode(OPENING_CURLY)}
+            </span>
+            {fields.map((detailRow, index) => (
```
Comment (dompuiu) [inline src/view/actions/directCall.jsx:54]: You could try to use this component https://github.com/adobe/reactor-extension-core/blob/master/src/view/components/multipleItemEditor.jsx here.

**Comment by dompuiu** [comment]
Beside my 3 comments, I think it looks great! Nice job!

**Review by dompuiu — APPROVED** [review]
